# Generated by Django 3.1.2 on 2020-11-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='character',
            field=models.IntegerField(default=0),
        ),
    ]
