# Generated by Django 3.1.2 on 2020-11-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='standard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='weapon',
            field=models.IntegerField(default=0),
        ),
    ]
