# Generated by Django 3.1.2 on 2020-12-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201126_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='event',
            field=models.IntegerField(default=10),
        ),
    ]
