# Generated by Django 3.1.2 on 2020-12-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blessing',
            field=models.BooleanField(default=False),
        ),
    ]
