# Generated by Django 3.1.2 on 2020-12-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'date']},
        ),
    ]
